name: tests

on:
  push:         {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        go:   ["1.18.x", "1.19.x", "1.20.x"]
        arch: ["amd64", "386"]

    env:
      GOARCH: "${{matrix.arch}}"

    steps:
      - uses: actions/checkout@v2

      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{matrix.go}}

      - name: build
        run: make all

      - name: test
        run: ./test.sh

  staticcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
          install-go: false

  code-coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: send coverage
        env:
          COVERALLS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./coverage.sh --coveralls
